apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "wormsign.fullname" . }}
  labels:
    {{- include "wormsign.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "wormsign.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wormsign.serviceAccountName" . }}
    namespace: {{ include "wormsign.namespace" . }}
